### PR TITLE
Code update. Added more donation options

### PR DESCRIPTION
**Pull request by Dasoldier1**
This should be tested properly.
I have tested the code a bit and most should be working.
es.php is not complete.
All the donation options can be turned on or off in config.

### CODE REVIEW

**Comment by u3games** [comment]
Nice!!

I test this ;)

**Comment by Dasoldier1** [comment]
Captcha is still cached on client side. 
i'm aware of it.
Trying to make a enchant option ( with item names that are equipped)
Still working on it and it can take some time.

**Comment by u3games** [comment]
ok, no problem ^^

**Comment by Dasoldier1** [comment]
I need some info about item loc_data.
Does a character has a max of invertory slots ? or was this only based on weight ?
Sorry i forgot.

Enchant option is almost done in index.php and it will give the full item names ^^. after that ill start with the ipn.

Found any problems with the system ?
Since i dont run a server yet :P.
I will install a vm soon to test the code a bit better.
i'm only using a database with(navicat), ipn simulator and notepad ++ xD

Edit:
Can you check for me if those id's are still correct ? or are there more hero/cursed weapons added ?
`// Define cursed weapons ids
                                                                                                $bloodswordakamanah = 8689;
                                                                                                $demonicswordzariche = 8190;
                                                                                                // Define hero weapons ids
                                                                                                $heroweap1 = 6611;
                                                                                                $heroweap2 = 6612;
                                                                                                $heroweap3 = 6613;
                                                                                                $heroweap4 = 6614;
                                                                                                $heroweap5 = 6615;
                                                                                                $heroweap6 = 6616;
                                                                                                $heroweap7 = 6617;
                                                                                                $heroweap8 = 6618;
                                                                                                $heroweap9 = 6619;
                                                                                                $heroweap10 = 6620;
                                                                                                $heroweap11 = 6611;
                                                                                                $heroweap12 = 9388;
                                                                                                $heroweap13 = 9389;
                                                                                                $heroweap14 = 9390;`

**Comment by u3games** [comment]
# INFO TEST!

Panel all ok, nice work!!



---



---



But, in game... no send info.



No send sql info and..



No send item/karma/pk status :(

**Comment by Dasoldier1** [comment]
Any error in donate overview ?
if there is no error i think the ipn url is not correct.
sandbox mode will never give you the item in game.
You need to use ipn simulator for that and set the script on sandbox mode.
If a donation with money is made and the config is not on sandbox mode it should work

**Comment by u3games** [comment]
Yes IPN no work... It has never worked, all test with sandbox mode.

See this.. https://gist.github.com/u3games/bc12d2e4026149e4a592 work fine.

**Comment by Dasoldier1** [comment]
@lol yea i know,
Let me be clear.
If you wanna test the ipn you cannot use the website form.

This will work.
1: You need to go to and login: https://developer.paypal.com/webapps/developer/applications/ipn_simulator

2: Now set IPN handler URL like http://yourwebsite.com/u3g/system/ipn/ipn_donations.php

3: Transaction type: web accept

4: mc_gross: is donation amount like 10 look config

5: And now use custom field: 
Charactername|Coins
Charactername|Karma
Charactername|Pkpoints

There is a security reason why you cannot use the index form directly to call the ipn.
This will only work on a live system without sandbox enabled and using real money.

if you still dont get it then ill  explain more tommorrow, i need to sleep gn :P.

**Comment by u3games** [comment]
Mmmm.. ok, tomorrow ;)

Edit sandbox for test in live server, is best for test ;)

**Comment by Dasoldier1** [comment]
Yea, but if you wanna test the donation system in a live situation. 
Then you need to turn off sandbox and send a real donation. 
Only then the IPN will be verified. and the donation should work.
else you need to use the 5 steps ive typed earlyer.

**Comment by Dasoldier1** [comment]
Hey,
Already found out how to use the ipn simulator ?
For now i only test with the simulator
When the system is more updated ill make some real donations to test it out

**Comment by u3games** [comment]
no problem ;) merge ^^

**Comment by Dasoldier1** [comment]
I think its better to wait for a bit a couple of days.
This weekend i think, then ill have the enchant items working and then i will update it to github.

This is what you can do to test the ipn:
 login: https://developer.paypal.com/webapps/developer/applications/ipn_simulator

Step1: choose your ipn file and select web accept 
step1

step2: check if its instant, confirmed and verified
step2

step3: you can select every donation option just change mc_gross and custom field.
step3

Options for custom field:
Charactername|Coins
Charactername|Karma
Charactername|Pkpoints

Just change custom field to one of the above options.
And now use the donation amount on MC_GROSS field.

step4: submit

**Comment by u3games** [comment]
Ok, no problem ;)

Next week I test PR, nice work :D

**Comment by Dasoldier1** [comment]
After figuring alot of code out, ive made it work finally ^^.
Needs alot of testing and adjusting before commit.

**Comment by Dasoldier1** [comment]
This is how we can test enchant items trough ipn simulator.
Use the right mc_gross ( amount )

Type on custom field:
charname|Enchitems|Shirt
charname|Enchitems|Helmet
charname|Enchitems|Necklace
charname|Enchitems|Weapon
charname|Enchitems|FullarmorBreastplate
charname|Enchitems|Shield
charname|Enchitems|Ring1
charname|Enchitems|Ring2
charname|Enchitems|Earring1
charname|Enchitems|Earring2
charname|Enchitems|Gloves
charname|Enchitems|Leggings
charname|Enchitems|Boots
charname|Enchitems|Belt

**Comment by Dasoldier1** [comment]
I see i need to make amount donation checks in the ipn so people cannot get a donation costs 10 euro for 1 euro.
i will fix it by today or tommorrow, i hope :P

**Comment by Dasoldier1** [comment]
I have found some mistakes in the code.
tommorrow i will update it on github and i will add enchant all enquipped items option

**Comment by Dasoldier1** [comment]
Already done, I'm going to sleep have a good night and gl testing :P

**Comment by u3games** [comment]
wooooo!! nice!!!

**Comment by Dasoldier1** [comment]
Thanks ^^
I wont be coding that mutch this week. but when i have time i will update some more.
Like adding a telnet connection check in the index and ipn+log.

I still want to add some more options.
But then it needs some kind of a login form.

Maby ill create a login form for players only needed for these donation options.
donation options like enchant/coins/karma/pk can be used without using a username and password.
But using one of these you need to login and should require a secure connection ssl https:
Its always better to use a secure connection for this donation system.
gender change
name change
transfer character to another account
change main class

I will think about it. i'm not sure yet what to do.
First i will try to make the current script better.

The system should be tested, didnt got mutch time to test. i only tested some parts.

**Comment by u3games** [comment]
Any new? merge?

**Comment by Dasoldier1** [comment]
Yea i think its oke to merge.
Only some language file updates are needed.
I wont be coding mutch for awhile, but ill keep an eye out if problems are detected and try to fix them.
And when i have more time ill try to improve the code.

**Comment by Dasoldier1** [comment]
I could merge it but spanish is still missing and the enchant options should be tested trough the ipn simulator. have only tested 2 different body parts to check if it was inserting the correct information in my old l2j database.

**Comment by u3games** [comment]
Ok, merge ;)

No problem i fix spanish lang.

**Pull request merged**
