### PR TITLE
Code updates

### PR DESCRIPTION
**Pull request by u3games**
Added ip security so that not anyone can access this page see config.
Added a simple donation overview (admin panel).
Minor fix and up code.

### CODE REVIEW

**Comment by u3games** [comment]
# TEST DONATION PLAYER:
- Player donation system work, but no send sql/item to server-player.

**Comment by u3games** [comment]
# TEST DONATE OVERVIEW
- Add missing values in connect.php --> https://github.com/u3games/U3G_PayPal_System_MMORPG/commit/924e16b888ad11a099b40bc0807dbecfed7e28a9
- Minor fix language in admin login panel --> https://github.com/u3games/U3G_PayPal_System_MMORPG/commit/2c69a0d3327d10534075cc6fd0cb9ae05970d9ad
- Minor up address rewrite, add localhost --> https://github.com/u3games/U3G_PayPal_System_MMORPG/commit/64b6f925733b4756a63bd0643c49d5798dba8df5
- Error test:



No send info of donations.

> Column not found: 1054 Unknown column 'amountminfee' in 'field list'

**Comment by Dasoldier1** [comment]
is there something i need to do before this can be upped to master branch ?

Images/flag/nl.png is missing

**Comment by u3games** [comment]
@Dasoldier1 yes, fix this pls ;)

> Column not found: 1054 Unknown column 'amountminfee' in 'field list'

https://cloud.githubusercontent.com/assets/5102409/12643971/dfc2c85a-c5bf-11e5-82d5-c4e92a5fee70.png

**Comment by u3games** [comment]
Merge pull request, nice @Dasoldier1 ^^

**Comment by Dasoldier1** [comment]
Hey i see that i need to fix: Column not found: 1054 Unknown column 'amountminfee' in 'field list'.

You did not updated your database. 

I have added a column amountminfee in there.
The log_paypal_donations.sql is oke in the master branch.

**Pull request merged**
