### PR TITLE
Up By @dasoldier

### PR DESCRIPTION
**Pull request by u3games**
Added error logging.
Add more languages and fix text.
Created a simple donation overview page system/admin/donateoverview.php.
Added ip security so that not anyone can access this page see config.
Now you can actually see if you are in sandbox mode.
Edit and place connection.ini outside the public domain
Upgrade sql log.
Cleaned up.

### CODE REVIEW

**Comment by u3games** [comment]
connect.php delete? Now use *.ini

My error:

ERROR: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected 
No work .. :S

**Comment by Dasoldier1** [comment]
Yea ive deleted connect.php so i can store the database login credentials outside the public domain.
If its to mutch hassle i can put the old way back.
I dont have any errors on my system .
But we will figure it out. :)

Oke when do you get this error ?
when you insert your player name and press on submit ?
Does system/admin/donationoverview.php gives the same error ?

Try to change this line: index.php line 40.

//try to make connection
$connection = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);

to this:

//try to make connection
$connection = new PDO("mysql: host=$db_host;dbname=$db_name;", $db_user, $db_pass);

explain: i just added  ; after $db_name and i have added a space after mysql:.

I have read somewhere if you want to connect to an external database you need to add a space after mysql: 
otherwise it wont work mysql: host=$db_host.

i cannot really say if this solves the issue since my database is local.
If i use the space i cannot connect to the database. 

We will first fix the current issues before i'm going to commit more updates.
i will try to make it better but it will take some work maby, ill do it upcomming week.

**Comment by u3games** [comment]
@Dasoldier1 Yeah, no problem ^^

In my opinion, is best use "connect.php"

The error in my test is in line 30 of index.php

Warning: parse_ini_file(): Filename cannot be empty! in C:\wamp\www\paypal\index.php on line 30

**Comment by Dasoldier1** [comment]
I have changed the connection back.
please test it.
I hope everything will be working now.
After that i will make a 1 on 1 copy from your master branch and start making commits.

**Comment by u3games** [comment]
I can´t donwload.. pls up new pr ;)

**Pull request closed without merging**
